
server:
  port: 8880

spring:
  jpa:
    defer-datasource-initialization: true
  application:
    name: STUDENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8881/eureka
  istance:
    hostname: localhost

